# Generated by Django 3.1.7 on 2021-03-15 12:10

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(blank=True, help_text='Laissez ce champ vide', unique=True)),
                ('img', models.ImageField(upload_to='produit_img/')),
                ('img2', models.ImageField(upload_to='produit_img/')),
                ('img3', models.ImageField(upload_to='produit_img/')),
                ('img4', models.ImageField(upload_to='produit_img/')),
                ('resume', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField(verbose_name='description')),
                ('prix', models.IntegerField()),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('preference', models.BooleanField(default=False, help_text='Favoris', null=True)),
                ('promotion', models.IntegerField(help_text='Pourcentage de la promotion', null=True)),
                ('promos', models.BooleanField(default=False, null=True)),
                ('url_test', models.CharField(blank=True, max_length=100, null=True)),
                ('page_views', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('Mot_cles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorie.motcles')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorie.category')),
                ('themes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorie.theme')),
            ],
            options={
                'db_table': 'product',
                'ordering': ('title',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
