# Generated by Django 3.1.7 on 2021-03-16 02:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20210316_0301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preference',
            new_name='Like',
        ),
    ]
