
CATEGORIES = [
    ('WEBSITE', 'WEBSITE'),
    ('SOFTWARE', 'SOFTWARE'),
    ('MOBILE', 'MOBILE'),
    ('WEBAPP', 'WEBAPP'),
]

CATEGORIES_THEME = [
    ('CLAIRE', 'CLAIRE'),
    ('CLASSIC', 'CLASSIC'),
    ('SOMBRE', 'SOMBRE'),
]

CATEGORIES_MOT_CLE = [
    ('SANTE', 'SANTE'),
    ('EDUCATION', 'EDUCATION'),
    ('BUSINESS', 'BUSINESS'),
    ('AGRICULTURE', 'AGRICULTURE'),
    ('iNDUSTRIE', 'iNDUSTRIE'),
    ('TELECOMMUNICATION', 'TELECOMMUNICATION'),
    ('MEDIA', 'MEDIA'),
    ('E-COMMERCE', 'E-COMMERCE'),
    ('EVENEMENT', 'EVENEMENT'),
    ('TRANSPORT', 'TRANSPORT'),
    ('RESSOURCE HUMAINES', 'RESSOURCE HUMAINES'),
    ('BANK', 'BANK'),
    ('ONG', 'ONG'),
    ('ENTREPRISE', 'ENTREPRISE'),
    ('MINE', 'MINE'),
    ('HABILLEMENT', 'HABILLEMENT'),
    ('SALON', 'SALON'),
    ('SERVICE', 'SERVICE'),
]
